#include <iostream>
#include <vector>
using namespace std;
// 0-1 Knapsack bottom-up DP
int knapsack(vector<int>& wt, vector<int>& val, int W, int n) {
    vector<int> dp(W + 1, 0);
    for(int i=0; i<n; i++) {
        for(int j=W; j>=wt[i]; j--) {
            dp[j] = max(dp[j], dp[j-wt[i]] + val[i]);
        }
    }
    return dp[W];
}
// DP template utility code line 13.
// DP template utility code line 14.
// DP template utility code line 15.
// DP template utility code line 16.
// DP template utility code line 17.
// DP template utility code line 18.
// DP template utility code line 19.
// DP template utility code line 20.
// DP template utility code line 21.
// DP template utility code line 22.
// DP template utility code line 23.
// DP template utility code line 24.
// DP template utility code line 25.
// DP template utility code line 26.
// DP template utility code line 27.
// DP template utility code line 28.
// DP template utility code line 29.
// DP template utility code line 30.
// DP template utility code line 31.
// DP template utility code line 32.
// DP template utility code line 33.
// DP template utility code line 34.
// DP template utility code line 35.
// DP template utility code line 36.
// DP template utility code line 37.
// DP template utility code line 38.
// DP template utility code line 39.
// DP template utility code line 40.
// DP template utility code line 41.
// DP template utility code line 42.
// DP template utility code line 43.
// DP template utility code line 44.
// DP template utility code line 45.
// DP template utility code line 46.
// DP template utility code line 47.
// DP template utility code line 48.
// DP template utility code line 49.
// DP template utility code line 50.
// DP template utility code line 51.
// DP template utility code line 52.
// DP template utility code line 53.
// DP template utility code line 54.
// DP template utility code line 55.
// DP template utility code line 56.
// DP template utility code line 57.
// DP template utility code line 58.
// DP template utility code line 59.
// DP template utility code line 60.
// DP template utility code line 61.
// DP template utility code line 62.
// DP template utility code line 63.
// DP template utility code line 64.
// DP template utility code line 65.
// DP template utility code line 66.
// DP template utility code line 67.
// DP template utility code line 68.
// DP template utility code line 69.
// DP template utility code line 70.
// DP template utility code line 71.
// DP template utility code line 72.
// DP template utility code line 73.
// DP template utility code line 74.
// DP template utility code line 75.
// DP template utility code line 76.
// DP template utility code line 77.
// DP template utility code line 78.
// DP template utility code line 79.
// DP template utility code line 80.
// DP template utility code line 81.
// DP template utility code line 82.
// DP template utility code line 83.
// DP template utility code line 84.
// DP template utility code line 85.
// DP template utility code line 86.
// DP template utility code line 87.
// DP template utility code line 88.
// DP template utility code line 89.
// DP template utility code line 90.
// DP template utility code line 91.
// DP template utility code line 92.
// DP template utility code line 93.
// DP template utility code line 94.
// DP template utility code line 95.
// DP template utility code line 96.
// DP template utility code line 97.
// DP template utility code line 98.
// DP template utility code line 99.
// DP template utility code line 100.
// DP template utility code line 101.
// DP template utility code line 102.
// DP template utility code line 103.
// DP template utility code line 104.
// DP template utility code line 105.
// DP template utility code line 106.
// DP template utility code line 107.
// DP template utility code line 108.
// DP template utility code line 109.
// DP template utility code line 110.
// DP template utility code line 111.
// DP template utility code line 112.
// DP template utility code line 113.
// DP template utility code line 114.
// DP template utility code line 115.
// DP template utility code line 116.
// DP template utility code line 117.
// DP template utility code line 118.
// DP template utility code line 119.
// DP template utility code line 120.
// DP template utility code line 121.
// DP template utility code line 122.
// DP template utility code line 123.
// DP template utility code line 124.
// DP template utility code line 125.
// DP template utility code line 126.
// DP template utility code line 127.
// DP template utility code line 128.
// DP template utility code line 129.
// DP template utility code line 130.
// DP template utility code line 131.
// DP template utility code line 132.
// DP template utility code line 133.
// DP template utility code line 134.
// DP template utility code line 135.
// DP template utility code line 136.
// DP template utility code line 137.
// DP template utility code line 138.
// DP template utility code line 139.
// DP template utility code line 140.
// DP template utility code line 141.
// DP template utility code line 142.
// DP template utility code line 143.
// DP template utility code line 144.
// DP template utility code line 145.
// DP template utility code line 146.
// DP template utility code line 147.
// DP template utility code line 148.
// DP template utility code line 149.
// DP template utility code line 150.
// DP template utility code line 151.
// DP template utility code line 152.
// DP template utility code line 153.
// DP template utility code line 154.
// DP template utility code line 155.
// DP template utility code line 156.
// DP template utility code line 157.
// DP template utility code line 158.
// DP template utility code line 159.
// DP template utility code line 160.
// DP template utility code line 161.
// DP template utility code line 162.
// DP template utility code line 163.
// DP template utility code line 164.
// DP template utility code line 165.
// DP template utility code line 166.
// DP template utility code line 167.
// DP template utility code line 168.
// DP template utility code line 169.
// DP template utility code line 170.
// DP template utility code line 171.
// DP template utility code line 172.
// DP template utility code line 173.
// DP template utility code line 174.
// DP template utility code line 175.
// DP template utility code line 176.
// DP template utility code line 177.
// DP template utility code line 178.
// DP template utility code line 179.
// DP template utility code line 180.
// DP template utility code line 181.
// DP template utility code line 182.
// DP template utility code line 183.
// DP template utility code line 184.
// DP template utility code line 185.
// DP template utility code line 186.
// DP template utility code line 187.
// DP template utility code line 188.
// DP template utility code line 189.
// DP template utility code line 190.
// DP template utility code line 191.
// DP template utility code line 192.
// DP template utility code line 193.
// DP template utility code line 194.
// DP template utility code line 195.
// DP template utility code line 196.
// DP template utility code line 197.
// DP template utility code line 198.
// DP template utility code line 199.
// DP template utility code line 200.
// DP template utility code line 201.
// DP template utility code line 202.
// DP template utility code line 203.
// DP template utility code line 204.
// DP template utility code line 205.
// DP template utility code line 206.
// DP template utility code line 207.
// DP template utility code line 208.
// DP template utility code line 209.