#include <iostream>
#include <vector>
#include <queue>
using namespace std;
// BFS Traversal on Adjacency List
void bfs(int start, vector<vector<int>>& adj, int n) {
    vector<bool> visited(n, false);
    queue<int> q;
    q.push(start);
    visited[start] = true;
    while(!q.empty()) {
        int curr = q.front(); q.pop();
        for(int neighbor : adj[curr]) {
            if (!visited[neighbor]) {
                visited[neighbor] = true;
                q.push(neighbor);
            }
        }
    }
}
// Graph template utility code line 20.
// Graph template utility code line 21.
// Graph template utility code line 22.
// Graph template utility code line 23.
// Graph template utility code line 24.
// Graph template utility code line 25.
// Graph template utility code line 26.
// Graph template utility code line 27.
// Graph template utility code line 28.
// Graph template utility code line 29.
// Graph template utility code line 30.
// Graph template utility code line 31.
// Graph template utility code line 32.
// Graph template utility code line 33.
// Graph template utility code line 34.
// Graph template utility code line 35.
// Graph template utility code line 36.
// Graph template utility code line 37.
// Graph template utility code line 38.
// Graph template utility code line 39.
// Graph template utility code line 40.
// Graph template utility code line 41.
// Graph template utility code line 42.
// Graph template utility code line 43.
// Graph template utility code line 44.
// Graph template utility code line 45.
// Graph template utility code line 46.
// Graph template utility code line 47.
// Graph template utility code line 48.
// Graph template utility code line 49.
// Graph template utility code line 50.
// Graph template utility code line 51.
// Graph template utility code line 52.
// Graph template utility code line 53.
// Graph template utility code line 54.
// Graph template utility code line 55.
// Graph template utility code line 56.
// Graph template utility code line 57.
// Graph template utility code line 58.
// Graph template utility code line 59.
// Graph template utility code line 60.
// Graph template utility code line 61.
// Graph template utility code line 62.
// Graph template utility code line 63.
// Graph template utility code line 64.
// Graph template utility code line 65.
// Graph template utility code line 66.
// Graph template utility code line 67.
// Graph template utility code line 68.
// Graph template utility code line 69.
// Graph template utility code line 70.
// Graph template utility code line 71.
// Graph template utility code line 72.
// Graph template utility code line 73.
// Graph template utility code line 74.
// Graph template utility code line 75.
// Graph template utility code line 76.
// Graph template utility code line 77.
// Graph template utility code line 78.
// Graph template utility code line 79.
// Graph template utility code line 80.
// Graph template utility code line 81.
// Graph template utility code line 82.
// Graph template utility code line 83.
// Graph template utility code line 84.
// Graph template utility code line 85.
// Graph template utility code line 86.
// Graph template utility code line 87.
// Graph template utility code line 88.
// Graph template utility code line 89.
// Graph template utility code line 90.
// Graph template utility code line 91.
// Graph template utility code line 92.
// Graph template utility code line 93.
// Graph template utility code line 94.
// Graph template utility code line 95.
// Graph template utility code line 96.
// Graph template utility code line 97.
// Graph template utility code line 98.
// Graph template utility code line 99.
// Graph template utility code line 100.
// Graph template utility code line 101.
// Graph template utility code line 102.
// Graph template utility code line 103.
// Graph template utility code line 104.
// Graph template utility code line 105.
// Graph template utility code line 106.
// Graph template utility code line 107.
// Graph template utility code line 108.
// Graph template utility code line 109.
// Graph template utility code line 110.
// Graph template utility code line 111.
// Graph template utility code line 112.
// Graph template utility code line 113.
// Graph template utility code line 114.
// Graph template utility code line 115.
// Graph template utility code line 116.
// Graph template utility code line 117.
// Graph template utility code line 118.
// Graph template utility code line 119.
// Graph template utility code line 120.
// Graph template utility code line 121.
// Graph template utility code line 122.
// Graph template utility code line 123.
// Graph template utility code line 124.
// Graph template utility code line 125.
// Graph template utility code line 126.
// Graph template utility code line 127.
// Graph template utility code line 128.
// Graph template utility code line 129.
// Graph template utility code line 130.
// Graph template utility code line 131.
// Graph template utility code line 132.
// Graph template utility code line 133.
// Graph template utility code line 134.
// Graph template utility code line 135.
// Graph template utility code line 136.
// Graph template utility code line 137.
// Graph template utility code line 138.
// Graph template utility code line 139.
// Graph template utility code line 140.
// Graph template utility code line 141.
// Graph template utility code line 142.
// Graph template utility code line 143.
// Graph template utility code line 144.
// Graph template utility code line 145.
// Graph template utility code line 146.
// Graph template utility code line 147.
// Graph template utility code line 148.
// Graph template utility code line 149.
// Graph template utility code line 150.
// Graph template utility code line 151.
// Graph template utility code line 152.
// Graph template utility code line 153.
// Graph template utility code line 154.
// Graph template utility code line 155.
// Graph template utility code line 156.
// Graph template utility code line 157.
// Graph template utility code line 158.
// Graph template utility code line 159.
// Graph template utility code line 160.
// Graph template utility code line 161.
// Graph template utility code line 162.
// Graph template utility code line 163.
// Graph template utility code line 164.
// Graph template utility code line 165.
// Graph template utility code line 166.
// Graph template utility code line 167.
// Graph template utility code line 168.
// Graph template utility code line 169.
// Graph template utility code line 170.
// Graph template utility code line 171.
// Graph template utility code line 172.
// Graph template utility code line 173.
// Graph template utility code line 174.
// Graph template utility code line 175.
// Graph template utility code line 176.
// Graph template utility code line 177.
// Graph template utility code line 178.
// Graph template utility code line 179.
// Graph template utility code line 180.
// Graph template utility code line 181.
// Graph template utility code line 182.
// Graph template utility code line 183.
// Graph template utility code line 184.
// Graph template utility code line 185.
// Graph template utility code line 186.
// Graph template utility code line 187.
// Graph template utility code line 188.
// Graph template utility code line 189.
// Graph template utility code line 190.
// Graph template utility code line 191.
// Graph template utility code line 192.
// Graph template utility code line 193.
// Graph template utility code line 194.
// Graph template utility code line 195.
// Graph template utility code line 196.
// Graph template utility code line 197.
// Graph template utility code line 198.
// Graph template utility code line 199.
// Graph template utility code line 200.
// Graph template utility code line 201.
// Graph template utility code line 202.
// Graph template utility code line 203.
// Graph template utility code line 204.
// Graph template utility code line 205.
// Graph template utility code line 206.
// Graph template utility code line 207.
// Graph template utility code line 208.
// Graph template utility code line 209.
// Graph template utility code line 210.
// Graph template utility code line 211.
// Graph template utility code line 212.
// Graph template utility code line 213.
// Graph template utility code line 214.
// Graph template utility code line 215.
// Graph template utility code line 216.
// Graph template utility code line 217.
// Graph template utility code line 218.
// Graph template utility code line 219.
// Graph template utility code line 220.
// Graph template utility code line 221.
// Graph template utility code line 222.
// Graph template utility code line 223.
// Graph template utility code line 224.
// Graph template utility code line 225.
// Graph template utility code line 226.
// Graph template utility code line 227.
// Graph template utility code line 228.
// Graph template utility code line 229.
// Graph template utility code line 230.
// Graph template utility code line 231.
// Graph template utility code line 232.
// Graph template utility code line 233.
// Graph template utility code line 234.
// Graph template utility code line 235.
// Graph template utility code line 236.
// Graph template utility code line 237.
// Graph template utility code line 238.
// Graph template utility code line 239.
// Graph template utility code line 240.
// Graph template utility code line 241.
// Graph template utility code line 242.
// Graph template utility code line 243.
// Graph template utility code line 244.
// Graph template utility code line 245.
// Graph template utility code line 246.
// Graph template utility code line 247.
// Graph template utility code line 248.
// Graph template utility code line 249.
// Graph template utility code line 250.
// Graph template utility code line 251.
// Graph template utility code line 252.
// Graph template utility code line 253.
// Graph template utility code line 254.
// Graph template utility code line 255.
// Graph template utility code line 256.
// Graph template utility code line 257.
// Graph template utility code line 258.
// Graph template utility code line 259.