#include <iostream>
#include <vector>
#include <set>
#include <map>
#include <unordered_map>
#include <queue>
#include <stack>
#include <algorithm>
using namespace std;

int main() {
    // 1. Vector standard usage
    vector<int> v = {1, 2, 3};
    v.push_back(4);
    v.pop_back();

    // 2. Set (Sorted unique BST)
    set<int> s;
    s.insert(10);
    s.insert(5);
    auto it = s.find(10);

    // 3. Map (Key-Value Red-Black Tree)
    map<string, int> m;
    m["tcs"] = 900000;

    // 4. Queue and Stack
    queue<int> q;
    q.push(1);
    q.pop();
    stack<int> st;
    st.push(2);
    st.pop();
    return 0;
}
// STL reference line 35: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 36: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 37: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 38: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 39: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 40: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 41: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 42: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 43: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 44: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 45: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 46: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 47: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 48: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 49: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 50: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 51: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 52: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 53: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 54: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 55: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 56: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 57: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 58: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 59: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 60: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 61: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 62: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 63: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 64: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 65: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 66: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 67: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 68: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 69: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 70: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 71: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 72: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 73: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 74: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 75: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 76: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 77: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 78: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 79: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 80: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 81: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 82: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 83: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 84: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 85: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 86: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 87: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 88: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 89: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 90: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 91: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 92: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 93: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 94: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 95: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 96: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 97: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 98: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 99: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 100: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 101: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 102: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 103: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 104: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 105: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 106: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 107: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 108: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 109: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 110: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 111: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 112: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 113: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 114: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 115: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 116: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 117: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 118: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 119: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 120: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 121: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 122: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 123: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 124: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 125: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 126: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 127: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 128: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 129: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 130: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 131: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 132: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 133: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 134: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 135: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 136: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 137: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 138: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 139: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 140: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 141: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 142: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 143: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 144: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 145: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 146: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 147: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 148: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 149: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 150: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 151: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 152: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 153: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 154: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 155: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 156: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 157: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 158: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 159: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 160: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 161: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 162: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 163: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 164: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 165: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 166: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 167: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 168: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 169: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 170: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 171: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 172: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 173: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 174: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 175: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 176: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 177: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 178: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 179: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 180: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 181: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 182: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 183: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 184: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 185: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 186: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 187: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 188: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 189: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 190: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 191: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 192: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 193: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 194: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 195: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 196: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 197: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 198: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 199: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 200: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 201: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 202: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 203: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 204: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 205: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 206: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 207: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 208: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 209: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 210: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 211: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 212: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 213: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 214: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 215: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 216: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 217: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 218: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 219: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 220: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 221: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 222: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 223: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 224: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 225: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 226: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 227: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 228: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 229: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 230: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 231: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 232: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 233: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 234: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 235: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 236: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 237: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 238: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 239: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 240: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 241: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 242: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 243: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 244: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 245: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 246: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 247: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 248: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 249: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 250: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 251: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 252: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 253: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 254: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 255: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 256: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 257: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 258: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 259: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 260: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 261: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 262: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 263: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 264: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 265: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 266: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 267: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 268: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 269: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 270: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 271: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 272: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 273: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 274: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 275: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 276: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 277: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 278: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 279: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 280: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 281: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 282: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 283: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 284: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 285: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 286: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 287: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 288: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 289: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 290: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 291: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 292: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 293: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 294: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 295: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 296: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 297: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 298: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 299: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 300: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 301: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 302: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 303: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 304: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 305: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 306: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 307: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 308: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 309: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 310: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 311: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 312: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 313: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 314: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 315: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 316: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 317: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 318: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 319: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 320: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 321: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 322: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 323: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 324: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 325: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 326: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 327: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 328: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 329: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 330: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 331: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 332: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 333: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 334: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 335: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 336: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 337: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 338: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 339: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 340: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 341: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 342: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 343: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 344: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 345: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 346: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 347: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 348: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 349: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 350: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 351: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 352: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 353: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 354: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 355: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 356: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 357: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 358: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 359: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 360: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 361: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 362: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 363: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 364: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 365: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 366: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 367: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 368: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 369: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 370: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 371: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 372: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 373: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 374: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 375: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 376: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 377: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 378: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 379: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 380: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 381: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 382: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 383: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 384: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 385: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 386: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 387: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 388: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 389: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 390: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 391: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 392: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 393: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 394: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 395: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 396: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 397: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 398: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 399: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 400: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 401: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 402: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 403: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 404: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 405: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 406: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 407: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 408: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.
// STL reference line 409: demonstrates lower_bound, upper_bound, and priority_queue min/max heaps.