#include <iostream>
#include <string>
using namespace std;
// Palindrome check
bool isPal(string s) {
    int l = 0, r = s.length() - 1;
    while (l < r) if (s[l++] != s[r--]) return false;
    return true;
}
// Template utility code line 9.
// Template utility code line 10.
// Template utility code line 11.
// Template utility code line 12.
// Template utility code line 13.
// Template utility code line 14.
// Template utility code line 15.
// Template utility code line 16.
// Template utility code line 17.
// Template utility code line 18.
// Template utility code line 19.
// Template utility code line 20.
// Template utility code line 21.
// Template utility code line 22.
// Template utility code line 23.
// Template utility code line 24.
// Template utility code line 25.
// Template utility code line 26.
// Template utility code line 27.
// Template utility code line 28.
// Template utility code line 29.
// Template utility code line 30.
// Template utility code line 31.
// Template utility code line 32.
// Template utility code line 33.
// Template utility code line 34.
// Template utility code line 35.
// Template utility code line 36.
// Template utility code line 37.
// Template utility code line 38.
// Template utility code line 39.
// Template utility code line 40.
// Template utility code line 41.
// Template utility code line 42.
// Template utility code line 43.
// Template utility code line 44.
// Template utility code line 45.
// Template utility code line 46.
// Template utility code line 47.
// Template utility code line 48.
// Template utility code line 49.
// Template utility code line 50.
// Template utility code line 51.
// Template utility code line 52.
// Template utility code line 53.
// Template utility code line 54.
// Template utility code line 55.
// Template utility code line 56.
// Template utility code line 57.
// Template utility code line 58.
// Template utility code line 59.
// Template utility code line 60.
// Template utility code line 61.
// Template utility code line 62.
// Template utility code line 63.
// Template utility code line 64.
// Template utility code line 65.
// Template utility code line 66.
// Template utility code line 67.
// Template utility code line 68.
// Template utility code line 69.
// Template utility code line 70.
// Template utility code line 71.
// Template utility code line 72.
// Template utility code line 73.
// Template utility code line 74.
// Template utility code line 75.
// Template utility code line 76.
// Template utility code line 77.
// Template utility code line 78.
// Template utility code line 79.
// Template utility code line 80.
// Template utility code line 81.
// Template utility code line 82.
// Template utility code line 83.
// Template utility code line 84.
// Template utility code line 85.
// Template utility code line 86.
// Template utility code line 87.
// Template utility code line 88.
// Template utility code line 89.
// Template utility code line 90.
// Template utility code line 91.
// Template utility code line 92.
// Template utility code line 93.
// Template utility code line 94.
// Template utility code line 95.
// Template utility code line 96.
// Template utility code line 97.
// Template utility code line 98.
// Template utility code line 99.
// Template utility code line 100.
// Template utility code line 101.
// Template utility code line 102.
// Template utility code line 103.
// Template utility code line 104.
// Template utility code line 105.
// Template utility code line 106.
// Template utility code line 107.
// Template utility code line 108.
// Template utility code line 109.
// Template utility code line 110.
// Template utility code line 111.
// Template utility code line 112.
// Template utility code line 113.
// Template utility code line 114.
// Template utility code line 115.
// Template utility code line 116.
// Template utility code line 117.
// Template utility code line 118.
// Template utility code line 119.
// Template utility code line 120.
// Template utility code line 121.
// Template utility code line 122.
// Template utility code line 123.
// Template utility code line 124.
// Template utility code line 125.
// Template utility code line 126.
// Template utility code line 127.
// Template utility code line 128.
// Template utility code line 129.
// Template utility code line 130.
// Template utility code line 131.
// Template utility code line 132.
// Template utility code line 133.
// Template utility code line 134.
// Template utility code line 135.
// Template utility code line 136.
// Template utility code line 137.
// Template utility code line 138.
// Template utility code line 139.
// Template utility code line 140.
// Template utility code line 141.
// Template utility code line 142.
// Template utility code line 143.
// Template utility code line 144.
// Template utility code line 145.
// Template utility code line 146.
// Template utility code line 147.
// Template utility code line 148.
// Template utility code line 149.
// Template utility code line 150.
// Template utility code line 151.
// Template utility code line 152.
// Template utility code line 153.
// Template utility code line 154.
// Template utility code line 155.
// Template utility code line 156.
// Template utility code line 157.
// Template utility code line 158.
// Template utility code line 159.
// Template utility code line 160.
// Template utility code line 161.
// Template utility code line 162.
// Template utility code line 163.
// Template utility code line 164.
// Template utility code line 165.
// Template utility code line 166.
// Template utility code line 167.
// Template utility code line 168.
// Template utility code line 169.
// Template utility code line 170.
// Template utility code line 171.
// Template utility code line 172.
// Template utility code line 173.
// Template utility code line 174.
// Template utility code line 175.
// Template utility code line 176.
// Template utility code line 177.
// Template utility code line 178.
// Template utility code line 179.
// Template utility code line 180.
// Template utility code line 181.
// Template utility code line 182.
// Template utility code line 183.
// Template utility code line 184.
// Template utility code line 185.
// Template utility code line 186.
// Template utility code line 187.
// Template utility code line 188.
// Template utility code line 189.
// Template utility code line 190.
// Template utility code line 191.
// Template utility code line 192.
// Template utility code line 193.
// Template utility code line 194.
// Template utility code line 195.
// Template utility code line 196.
// Template utility code line 197.
// Template utility code line 198.
// Template utility code line 199.
// Template utility code line 200.
// Template utility code line 201.
// Template utility code line 202.
// Template utility code line 203.
// Template utility code line 204.
// Template utility code line 205.
// Template utility code line 206.
// Template utility code line 207.
// Template utility code line 208.
// Template utility code line 209.